trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Instalar dependencias y compilar
- script: |
    npm install
    npm run build
  displayName: 'Instalar dependencias y compilar'

# Publicar archivos como ZIP para despliegue
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Crear paquete ZIP'

# Desplegar en Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'SAL'
    appName: 'S-A-L'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Desplegar en Azure Web App'
